# Generated by Django 4.1.3 on 2023-02-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_it_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Faible')], default='medium', max_length=20),
        ),
    ]
